﻿level-name: 遥不可及
level-dest-time: 7.0
player-spawn-target: spawn
level-border-height: 2.5
wall-style: Wall02
floor-style: Floor01
base-height: 2.5
fork-activator: true
level-end-target: end
audio:
 - ~/Audio/toki.ogg
 - ~/Audio/xueyang.ogg
 - ~/Audio/hgtc.ogg
 - ~/Audio/nightwalk.ogg
 - ~/Audio/toki1.ogg
light: 2
